export const actionTypes = {
	LOAD_DATA: "LOAD_DATA",
	FILTER: "FILTER",
	SET_LIKES: "SET_LIKES",
	SET_WATCHLATER: "SET_WATCHLATER",
	SET_HISTORY: "SET_HISTORY",
	SET_PLAYLISTS: "SET_PLAYLISTS",
	SET_PLAYLIST: "SET_PLAYLIST",
	SORT_VIDEOS: "SORT_VIDEOS",
	SET_VIDEOS: "SET_VIDEOS",
	SET_NOTES: "SET_NOTES",
	SEARCH: "SEARCH",
};
